services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: base_user
      POSTGRES_PASSWORD: strongpassword  # Replace with a secure password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - os-msa-poc-network
  nats:
    image: nats:2.14-scratch
    ports:
      - "4222:4222"
      - "8080:8080" # Monitoring port
    env_file:
      - .env
    volumes:
      - ./nats.conf:/etc/nats/nats.conf:ro
    networks:
      - os-msa-poc-network
    command: -config /etc/nats/nats.conf
  nats-redirect:
    image: ezenki/nats-auth-redirector:latest
    depends_on:
      - nats
    env_file:
      - .env
    networks:
      - os-msa-poc-network

networks:
  os-msa-poc-network:
    name: os-msa-poc-network