authorization {
  auth_callout {
    issuer: $ACCOUNT_SIGNER_PUB
    account: AUTH
    auth_users: [ "auth" ]
  }
}
accounts {
  AUTH: { users: [{ user: "auth", password: "auth" }] }
  APP: {}
  SYS: {}
}
system_account: SYS
websocket { 
    port: 8080 
    no_tls: true
}
