authorization {
  auth_callout {
    issuer: $ACCOUNT_SIGNER_PUB
    account: AUTH
    auth_users: [ "auth", "publisher" ]
  }
}

accounts {
  AUTH: {
    users: [
      { user: "auth", password: $NATS_AUTH_PASSWORD }
    ]
  }
  APP: {
    users: [
      {
        user: "publisher"
        password: $NATS_PUBLISH_PASSWORD
        permissions: {
          publish: { allow: [ "devices.created", "devices.*.measurements" ] }
          subscribe: { deny: [ ">" ] }
        }
      }
    ]
  }
  SYS: {}
}

system_account: SYS

websocket {
  port: 8080
  no_tls: true
}
