# Generated by Django 5.2.16 on 2026-07-26 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("key_ciphertext", models.BinaryField()),
                ("key_nonce", models.BinaryField()),
                ("next_entry_index", models.PositiveBigIntegerField(default=1)),
                ("enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entry_index", models.PositiveBigIntegerField()),
                ("measurement_name", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                ("measured_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measurements",
                        to="devices.device",
                    ),
                ),
            ],
            options={
                "ordering": ["device_id", "entry_index"],
            },
        ),
        migrations.DeleteModel(
            name="DeviceData",
        ),
        migrations.AddIndex(
            model_name="measurement",
            index=models.Index(
                fields=["device", "-entry_index"],
                name="devices_mea_device__26216d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="measurement",
            constraint=models.UniqueConstraint(
                fields=("device", "entry_index"),
                name="devices_unique_measurement_entry_index",
            ),
        ),
    ]
