services:
  api:
    image: python:3.13-slim
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    working_dir: /app
    command: ["/bin/sh", "-lc", ". ./start.sh"]
    env_file:
      - ../.env
    networks:
      - os-msa-poc-network

networks:
  os-msa-poc-network:
    external: true
    name: os-msa-poc-network
