"""
Django settings for testsite project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", 'django-insecure-5twbbb8e5=r7l*oyxrqznd@*hjt_6f_38%t2acq-m%=ijswjz6')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get(
        "DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1,django"
    ).split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # "mozilla_django_oidc",
    "rest_framework",
    "rest_framework.authtoken",
    'django.contrib.staticfiles',
    'devices.apps.DevicesConfig',
    "nats_auth"
]

# AUTHENTICATION_BACKENDS = [
#     "mozilla_django_oidc.auth.OIDCAuthenticationBackend",
#     "django.contrib.auth.backends.ModelBackend",  # keep for superuser/staff perms
# ]


# LOGIN_URL = "/oidc/authenticate/"          # triggers OIDC login
# LOGIN_REDIRECT_URL = "/"                   # after successful login
# LOGOUT_REDIRECT_URL = "/"                  # after logout

# # OIDC provider (Keycloak)
# OIDC_OP_ISSUER = os.getenv("OIDC_ISSUER")                  # e.g. https://keycloak/.../realms/msa-poc
# OIDC_RP_CLIENT_ID = os.getenv("OIDC_CLIENT_ID")
# OIDC_RP_CLIENT_SECRET = os.getenv("OIDC_CLIENT_SECRET")
# OIDC_RP_SCOPES = "openid email profile"
# OIDC_STORE_ID_TOKEN = True
# OIDC_USE_NONCE = True

# # Map claims to Django user fields
# OIDC_USERNAME_ALGO = "mozilla_django_oidc.auth.DefaultUsernameAlgorithm"
# OIDC_CLAIMS_VERIFICATION = True

# # Sessions: keep client-side signed cookies (no server store)
# SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
# SESSION_COOKIE_SAMESITE = "Lax"           # "None"+Secure if cross-site
# SESSION_COOKIE_SECURE = False             # True in prod (HTTPS)
# CSRF_COOKIE_SECURE = False 

REST_FRAMEWORK = {
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
        "rest_framework.permissions.DjangoModelPermissions",
    ],
    # dev-friendly auth (you can swap in JWT later)
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware", 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

SIMPLE_JWT = {
    "ALGORITHM": "HS256",                       # or "RS256"
    "SIGNING_KEY": os.getenv("JWT_SIGNING_KEY", SECRET_KEY),
    "ACCESS_TOKEN_LIFETIME": timedelta(days=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=70),
}

ROOT_URLCONF = 'testsite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'testsite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get("POSTGRES_DB", "django_db"),
        'USER': os.environ.get("POSTGRES_USER", "base_user"),
        'PASSWORD': os.environ.get("POSTGRES_PASSWORD", "strongpassword"),
        'HOST': os.environ.get("POSTGRES_HOST", "postgres"),
        'PORT': os.environ.get("POSTGRES_PORT", '5432')
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"  # where collectstatic will put files

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DEVICE_KEY_ENCRYPTION_KEY = os.environ.get("DEVICE_KEY_ENCRYPTION_KEY", "")

NATS_PUBLISH_URL = os.environ.get(
    "NATS_PUBLISH_URL", "nats://publisher:publisher@nats:4222"
)
